### ISSUE TITLE
Correções Ortográficas no Site

### ISSUE THREAD

**Issue by AffonsoGiesel** [Caua539/integracao2017#17]
### Apresentação do Curso 
linha 2 - (PPCi criada em 2008) -> PPC
linha 4 - falta de ponto final
3º parágrafo linha 2 - refinados.Os -> Espaçamento
4º parágrafo linha 1 - significativas.Em -> Espaçamento
4º parágrafo linha 2 - computação.A -> Espaçamento
4º parágrafo linha 3 - intetegrador -> integrador
4º parágrafo linha 6 - adiquiridas -> adquiridas

**Comment by NataliaMarufuji** [comment]
Done
