### ISSUE TITLE
Disciplinas optativas constam como obrigatórias em sua descrição

### ISSUE THREAD

**Issue by DevCaua** [Caua539/integracao2017#23]

**Comment by ghost** [comment]
Corrigi as matérias **Mercado e economia de software** e **Experimentação em engenharia de software**.

Enquanto estava fazendo o levantamento, verifiquei que algumas matérias optativas não estavam presentes na tabela.

**Comment by DevCaua** [comment]
Vou deixar aberta até eu corrigir isso no código
